################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_SRCS := 
CPP_SRCS := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
jni/src/windows/library/src/OpenGL \
jni/src/windows \
jni/src/tfw/ui \
jni/src/tfw/txt/implement \
jni/src/tfw/txt \
jni/src/tfw/tbf \
jni/src/tfw/string \
jni/src/tfw/sound \
jni/src/tfw/smenu \
jni/src/tfw/serialize \
jni/src/tfw/psns \
jni/src/tfw/modemng \
jni/src/tfw/lib \
jni/src/tfw/image \
jni/src/tfw/hash \
jni/src/tfw/gui/txtbox \
jni/src/tfw/gui \
jni/src/tfw/gcmn \
jni/src/tfw/g3d/sg/node/implement \
jni/src/tfw/g3d/sg/node \
jni/src/tfw/g3d/sg \
jni/src/tfw/g3d \
jni/src/tfw/g2d/font/implement \
jni/src/tfw/g2d/font \
jni/src/tfw/g2d \
jni/src/tfw/framemod \
jni/src/tfw/file \
jni/src/tfw/evsys \
jni/src/tfw/downloader \
jni/src/tfw/debug \
jni/src/tfw/common \
jni/src/tfw/collision \
jni/src/tfw \
jni/src/sourcerer/unit/item \
jni/src/sourcerer/unit/char/pc \
jni/src/sourcerer/unit/char/npc \
jni/src/sourcerer/unit/char \
jni/src/sourcerer/unit \
jni/src/sourcerer/status \
jni/src/sourcerer/spirit/char/pc \
jni/src/sourcerer/spirit/char/npc \
jni/src/sourcerer/spirit \
jni/src/sourcerer/source \
jni/src/sourcerer/sound \
jni/src/sourcerer/souma/script \
jni/src/sourcerer/souma \
jni/src/sourcerer/save \
jni/src/sourcerer/quest/qsmod \
jni/src/sourcerer/quest/qsemp/implement \
jni/src/sourcerer/quest/qsemp \
jni/src/sourcerer/quest \
jni/src/sourcerer/purepuzzle \
jni/src/sourcerer/particle/progptclmdl/implement \
jni/src/sourcerer/particle/progptclmdl \
jni/src/sourcerer/particle \
jni/src/sourcerer/model/spid \
jni/src/sourcerer/model \
jni/src/sourcerer/mode/title \
jni/src/sourcerer/mode/startgame \
jni/src/sourcerer/mode/purepuzzle/menu \
jni/src/sourcerer/mode/purepuzzle \
jni/src/sourcerer/mode/ingame/worldmap \
jni/src/sourcerer/mode/ingame/walking \
jni/src/sourcerer/mode/ingame/menu \
jni/src/sourcerer/mode/ingame/event \
jni/src/sourcerer/mode/ingame/confront \
jni/src/sourcerer/mode/ingame \
jni/src/sourcerer/mode/bookview \
jni/src/sourcerer/mode \
jni/src/sourcerer/map \
jni/src/sourcerer/magic/implement \
jni/src/sourcerer/magic \
jni/src/sourcerer/item \
jni/src/sourcerer/gui/window/menu/implement \
jni/src/sourcerer/gui/window/menu \
jni/src/sourcerer/gui/window/implement \
jni/src/sourcerer/gui/window \
jni/src/sourcerer/gui/panel \
jni/src/sourcerer/gui/menu/materialized \
jni/src/sourcerer/gui/menu \
jni/src/sourcerer/gui \
jni/src/sourcerer/file \
jni/src/sourcerer/event/matter/implement/act/implement \
jni/src/sourcerer/event/matter/implement/act \
jni/src/sourcerer/event/matter/implement \
jni/src/sourcerer/event/matter \
jni/src/sourcerer/event \
jni/src/sourcerer/es/kwset \
jni/src/sourcerer/es \
jni/src/sourcerer/episode/worldmap/implement \
jni/src/sourcerer/episode/worldmap \
jni/src/sourcerer/episode/stmod/implement \
jni/src/sourcerer/episode/stmod \
jni/src/sourcerer/episode/stemp/implement \
jni/src/sourcerer/episode/stemp \
jni/src/sourcerer/episode/save \
jni/src/sourcerer/episode/qsmod/implement \
jni/src/sourcerer/episode/qsmod \
jni/src/sourcerer/episode/qsemp/implement \
jni/src/sourcerer/episode/qsemp \
jni/src/sourcerer/episode/party \
jni/src/sourcerer/episode/mapmod/implement \
jni/src/sourcerer/episode/mapmod \
jni/src/sourcerer/episode/mapemp/implement \
jni/src/sourcerer/episode/mapemp \
jni/src/sourcerer/episode/data \
jni/src/sourcerer/episode/char/pc \
jni/src/sourcerer/episode/char/enemy \
jni/src/sourcerer/episode/char \
jni/src/sourcerer/episode \
jni/src/sourcerer/effect \
jni/src/sourcerer/debug/mode/txteditor \
jni/src/sourcerer/debug/mode/modelview \
jni/src/sourcerer/debug/mode \
jni/src/sourcerer/debug \
jni/src/sourcerer/confront \
jni/src/sourcerer/common \
jni/src/sourcerer/char \
jni/src/sourcerer/camera \
jni/src/sourcerer/bookviewer \
jni/src/sourcerer/body \
jni/src/etk/sound \
jni/src/etk/sg \
jni/src/etk/particle \
jni/src/etk/gui/window/implement \
jni/src/etk/gui/window \
jni/src/etk/gui \
jni/src/etk/effect \
jni/src/etk/debug \
jni/src/etk/common \
jni/src/etk/camera \
jni/src/etk/body \
jni/src/edev/particle \
jni/src/edev/gui \
jni/src/edev/file \
jni/src/edev/debug \
jni/src/edev/body \
jni/src/dimz/particle \
jni/src/dimz/mode \
jni/src/dimz/gui \
jni/src/dimz/file \
jni/src/dimz/debug \
jni/src/dimz/body \
jni/src/common/library/src/zlib \
jni/src/common/library/src/lpng \
jni/src/common/library/src/dtoa \
jni/src/basicmodel/gui \
jni/src/basicmodel/file \
jni/src/basicmodel/debug \
jni/src/basicmodel/body \
jni/src/atar/gui/window/implement \
jni/src/atar/gui \
jni/src/atar/file \
jni/src/atar/debug \
jni/src/atar/camera \
jni/src/atar/body \
jni/src/android \
jni/src/android/library/src/OpenAL/OpenAL32 \
jni/src/android/library/src/OpenAL/Alc \
jni/src/android/library/src/OpenAL/Alc/backends \

